# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for managed runs. These include runs against
# the localdocker, remotedocker, and cluster compute targets.

# Note that this file is NOT used to automatically manage dependencies for the
# local compute target. To provision these dependencies locally, run:
# conda env update --file conda_dependencies.yml

# Details about the Conda environment file format:
# https://conda.io/docs/using/envs.html#create-environment-file-by-hand

# For managing Spark packages and configuration, see spark_dependencies.yml.
# Version of this configuration file's structure and semantics in AzureML.
# This directive is stored in a comment to preserve the Conda file structure.
# [AzureMlVersion] = 2
name: amlproj06_training_env
dependencies:
  - python=3.10
  - pip=23.2.1

  - pip:
      # Base SDK AzureML
      - azureml-core==1.60.0
      - azureml-defaults==1.60.0
      - azureml-sdk==1.60.0

      # ML core
      - numpy==1.23.5
      - scikit-learn==1.4.2
      - pandas==2.2.2
      - lightgbm==4.3.0
      - joblib==1.3.2

      # Scoring
      - inference-schema[numpy-support]

      # Storage
      - azure-storage-blob


